server:
  port: 8080

spring:
  application:
    name: customer-ingestion-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

kafka:
  topics:
    customer-raw: customer.raw

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p){blue} %clr([%t]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: INFO
    com.mdm: DEBUG
