/*
 * Copyright © 2026. All rights reserved.
 * This code is for demonstration purposes only.
 */
package com.mdm.ingestion.service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.HexFormat;
import java.util.Optional;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.mdm.ingestion.entity.IdempotencyKey;
import com.mdm.ingestion.entity.IdempotencyKey.IdempotencyStatus;
import com.mdm.ingestion.repository.IdempotencyKeyRepository;
import com.mdm.ingestion.util.IdempotencyKeyGenerator;
import com.mdm.ingestion.util.SensitiveDataMasker;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/**
 * Manages idempotency key lifecycle using a dual-key strategy.
 *
 * <p>This service implements the idempotency resolution workflow:
 *
 * <ol>
 *   <li>If client provides X-Idempotency-Key: check it first
 *   <li>If client key is new/unique: allow the request (skip deterministic check)
 *   <li>If NO client key: check deterministic key (payload-based deduplication)
 *   <li>If deterministic key is COMPLETED → return cached response
 *   <li>If neither exists → insert new record
 * </ol>
 *
 * <p>The deterministic key (SHA-256 of nationalId|sourceSystem) is only checked when the client
 * does NOT provide their own idempotency key. This allows clients to send multiple different
 * requests for the same nationalId+sourceSystem by providing unique idempotency keys for each
 * request.
 */
@Slf4j
@RequiredArgsConstructor
@Service
public class IdempotencyService {

  private final IdempotencyKeyRepository repository;
  private final Clock clock;

  @Value("${idempotency.key.ttl-hours:24}")
  private long clientProvidedTtlHours;

  @Value("${idempotency.key.auto-generated-ttl-hours:6}")
  private long autoGeneratedTtlHours;

  /**
   * Resolves idempotency using the dual-key strategy.
   *
   * @param clientProvidedKey the optional client-provided idempotency key header
   * @param nationalId the normalized national ID (serves as unique identifier)
   * @param sourceSystem the originating source system
   * @return the idempotency result indicating how to proceed
   */
  @Transactional
  public IdempotencyResult processKey(
      String clientProvidedKey, String nationalId, String sourceSystem) {
    String deterministicKey = resolveDeterministicKey(nationalId, sourceSystem);
    Instant now = Instant.now(clock);

    // Step 1: If client provided a key, check it
    if (hasValue(clientProvidedKey)) {
      Optional<IdempotencyResult> clientResult =
          lookupByKey(clientProvidedKey, deterministicKey, now);
        return clientResult.orElseGet(() -> insertNewKey(clientProvidedKey, deterministicKey, now));
      // Client key is new and unique - allow the request WITHOUT checking deterministic key
      // This enables sending different payloads for same nationalId+sourceSystem
    }

    // Step 2: NO client key - check deterministic key for payload deduplication
    Optional<IdempotencyResult> deterministicResult =
        lookupByKey(deterministicKey, deterministicKey, now);
      return deterministicResult.orElseGet(() -> insertNewKey(null, deterministicKey, now));

    // Step 3: No existing key found — insert new record with deterministic key
  }

  /**
   * Marks an idempotency key as successfully completed.
   *
   * @param keyHash the SHA-256 hash of the deterministic key
   * @param eventId the event ID that was published
   */
  @Transactional
  public void completeKey(String keyHash, UUID eventId) {
    repository.completeByKeyHash(keyHash, IdempotencyStatus.COMPLETED);
    log.info(
        "Idempotency key completed: keyHash={}, eventId={}",
        SensitiveDataMasker.maskHash(keyHash),
        eventId);
  }

  /**
   * Marks an idempotency key as failed (allowing retry after backoff period).
   *
   * @param keyHash the SHA-256 hash of the deterministic key
   * @param eventId the event ID that failed
   */
  @Transactional
  public void failKey(String keyHash, UUID eventId) {
    int updated = repository.completeByKeyHash(keyHash, IdempotencyStatus.FAILED);
    if (updated > 0) {
      log.warn(
          "Idempotency key marked failed: keyHash={}, eventId={}",
          SensitiveDataMasker.maskHash(keyHash),
          eventId);
    } else {
      log.debug(
          "Idempotency key was not in PROCESSING state, skip fail: keyHash={}",
          SensitiveDataMasker.maskHash(keyHash));
    }
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  private Optional<IdempotencyResult> lookupByKey(
      String lookupKey, String deterministicKey, Instant now) {
    // Use pessimistic locking to prevent race conditions
    Optional<IdempotencyKey> found = repository.findByKeyHashForUpdate(lookupKey);
    if (found.isEmpty()) {
      found = repository.findByClientIdempotencyKeyForUpdate(lookupKey);
    }

    if (found.isEmpty()) {
      return Optional.empty();
    }

    IdempotencyKey key = found.get();

    if (key.isExpiredAt(now)) {
      log.info(
          "Idempotency key expired: lookupKey={}, deterministicKey={}, expiresAt={}",
          SensitiveDataMasker.maskHash(lookupKey),
          SensitiveDataMasker.maskHash(deterministicKey),
          key.getExpiresAt());
      return Optional.of(IdempotencyResult.expired(deterministicKey));
    }

    if (key.getStatus() == IdempotencyStatus.COMPLETED) {
      log.info(
          "Idempotency key hit: lookupKey={}, deterministicKey={}, eventId={}",
          SensitiveDataMasker.maskHash(lookupKey),
          SensitiveDataMasker.maskHash(deterministicKey),
          key.getEventId());
      return Optional.of(IdempotencyResult.hit(deterministicKey, key.getEventId()));
    }

    log.info(
        "Idempotency key still processing: lookupKey={}, deterministicKey={}",
        SensitiveDataMasker.maskHash(lookupKey),
        SensitiveDataMasker.maskHash(deterministicKey));
    return Optional.of(IdempotencyResult.processing(deterministicKey));
  }

  private IdempotencyResult insertNewKey(
      String clientProvidedKey, String deterministicKey, Instant now) {
    UUID eventId = UUID.randomUUID();
    Duration ttl = calculateTtl(clientProvidedKey);
    Instant expiresAt = now.plus(ttl);

    // When client provides a key, use client key hash as primary key to allow
    // multiple different requests for same nationalId+sourceSystem
    String primaryHash =
        hasValue(clientProvidedKey) ? hashClientKey(clientProvidedKey) : deterministicKey;

    int inserted =
        repository.insertIfNotExists(
            primaryHash,
            clientProvidedKey,
            eventId,
            IdempotencyStatus.PROCESSING.name(),
            now,
            expiresAt);

    if (inserted > 0) {
      log.info(
          "Idempotency key miss (new): primaryHash={}, deterministicKey={}, clientKey={}, eventId={}, ttl={}",
          SensitiveDataMasker.maskHash(primaryHash),
          SensitiveDataMasker.maskHash(deterministicKey),
          SensitiveDataMasker.maskHash(clientProvidedKey),
          eventId,
          ttl.toHours() + "h");
      return IdempotencyResult.miss(primaryHash, eventId);
    }

    return handleConcurrentInsert(primaryHash);
  }

  private IdempotencyResult handleConcurrentInsert(String primaryHash) {
    IdempotencyKey concurrentKey =
        repository
            .findByKeyHash(primaryHash)
            .orElseThrow(() -> new IllegalStateException("Key should exist after failed insert"));

    if (concurrentKey.getStatus() == IdempotencyStatus.COMPLETED) {
      log.info(
          "Idempotency key hit (concurrent): keyHash={}, eventId={}",
          SensitiveDataMasker.maskHash(primaryHash),
          concurrentKey.getEventId());
      return IdempotencyResult.hit(primaryHash, concurrentKey.getEventId());
    }

    log.info(
        "Idempotency key still processing (concurrent): keyHash={}",
        SensitiveDataMasker.maskHash(primaryHash));
    return IdempotencyResult.processing(primaryHash);
  }

  /** Hashes a client-provided idempotency key for storage. */
  private String hashClientKey(String clientKey) {
    try {
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      byte[] hashBytes = digest.digest(clientKey.getBytes(StandardCharsets.UTF_8));
      return HexFormat.of().formatHex(hashBytes);
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException("SHA-256 algorithm not available", e);
    }
  }

  private Duration calculateTtl(String clientProvidedKey) {
    if (hasValue(clientProvidedKey)) {
      return Duration.ofHours(clientProvidedTtlHours);
    }
    return Duration.ofHours(autoGeneratedTtlHours);
  }

  private String resolveDeterministicKey(String nationalId, String sourceSystem) {
    return IdempotencyKeyGenerator.generate(nationalId, sourceSystem);
  }

  private static boolean hasValue(String value) {
    return value != null && !value.isBlank();
  }

  // ─── Sealed result types ───────────────────────────────────────────────────

  public sealed interface IdempotencyResult {
    String keyHash();

    UUID eventId();

    static IdempotencyResult hit(String keyHash, UUID eventId) {
      return new IdempotencyHit(keyHash, eventId);
    }

    static IdempotencyResult miss(String keyHash, UUID eventId) {
      return new IdempotencyMiss(keyHash, eventId);
    }

    static IdempotencyResult processing(String keyHash) {
      return new IdempotencyProcessing(keyHash);
    }

    static IdempotencyResult expired(String keyHash) {
      return new IdempotencyExpired(keyHash);
    }
  }

  public record IdempotencyHit(String keyHash, UUID eventId) implements IdempotencyResult {}

  public record IdempotencyMiss(String keyHash, UUID eventId) implements IdempotencyResult {}

  public record IdempotencyProcessing(String keyHash) implements IdempotencyResult {
    @Override
    public UUID eventId() {
      return null;
    }
  }

  public record IdempotencyExpired(String keyHash) implements IdempotencyResult {
    @Override
    public UUID eventId() {
      return null;
    }
  }
}
