/*
 * Copyright © 2026. All rights reserved.
 * This code is for demonstration purposes only.
 */
package com.mdm.ingestion.service;

import com.mdm.ingestion.entity.IdempotencyKey;
import com.mdm.ingestion.entity.IdempotencyKey.IdempotencyStatus;
import com.mdm.ingestion.repository.IdempotencyKeyRepository;
import com.mdm.ingestion.util.IdempotencyKeyGenerator;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Manages idempotency key lifecycle using a dual-key strategy.
 *
 * <p>This service implements the idempotency resolution workflow:
 * <ol>
 *   <li>Check client-provided key first (if present)</li>
 *   <li>Always check the deterministic key (payload-based deduplication)</li>
 *   <li>If either is COMPLETED → return cached response</li>
 *   <li>If either is PROCESSING → return 409 Conflict</li>
 *   <li>If neither exists → insert new record with deterministic key</li>
 * </ol>
 *
 * <p>This ensures that the same payload is never duplicated even when the client
 * sometimes sends the X-Idempotency-Key header and sometimes doesn't.
 */
@Slf4j
@RequiredArgsConstructor
@Service
public class IdempotencyService {

  private final IdempotencyKeyRepository repository;
  private final Clock clock;

  @Value("${idempotency.key.ttl-hours:24}")
  private long clientProvidedTtlHours;

  @Value("${idempotency.key.auto-generated-ttl-hours:6}")
  private long autoGeneratedTtlHours;

  /**
   * Resolves idempotency using the dual-key strategy.
   *
   * @param clientProvidedKey the optional client-provided idempotency key header
   * @param nationalId the normalized national ID (serves as unique identifier)
   * @param sourceSystem the originating source system
   * @return the idempotency result indicating how to proceed
   */
  @Transactional
  public IdempotencyResult processKey(
      String clientProvidedKey, String nationalId, String sourceSystem) {
    String deterministicKey = resolveDeterministicKey(nationalId, sourceSystem);
    Instant now = Instant.now(clock);

    // Step 1: Check client-provided key first (if present)
    if (hasValue(clientProvidedKey)) {
      Optional<IdempotencyResult> clientResult =
          lookupByKey(clientProvidedKey, deterministicKey, now);
      if (clientResult.isPresent()) {
        return clientResult.get();
      }
    }

    // Step 2: Check deterministic key
    Optional<IdempotencyResult> deterministicResult =
        lookupByKey(deterministicKey, deterministicKey, now);
    if (deterministicResult.isPresent()) {
      return deterministicResult.get();
    }

    // Step 3: Neither found — insert new record
    return insertNewKey(clientProvidedKey, deterministicKey, now);
  }

  /**
   * Marks an idempotency key as successfully completed.
   *
   * @param keyHash the SHA-256 hash of the deterministic key
   * @param eventId the event ID that was published
   */
  @Transactional
  public void completeKey(String keyHash, UUID eventId) {
    repository.completeByKeyHash(keyHash, IdempotencyStatus.COMPLETED);
    log.info("Idempotency key completed: keyHash={}, eventId={}", maskKey(keyHash), eventId);
  }

  /**
   * Marks an idempotency key as failed (preventing reprocessing).
   *
   * @param keyHash the SHA-256 hash of the deterministic key
   * @param eventId the event ID that failed
   */
  @Transactional
  public void failKey(String keyHash, UUID eventId) {
    repository.completeByKeyHash(keyHash, IdempotencyStatus.COMPLETED);
    log.warn("Idempotency key marked failed: keyHash={}, eventId={}", maskKey(keyHash), eventId);
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  private Optional<IdempotencyResult> lookupByKey(
      String lookupKey, String deterministicKey, Instant now) {
    Optional<IdempotencyKey> found = repository.findByKeyHash(lookupKey);
    if (found.isEmpty()) {
      found = repository.findByClientIdempotencyKey(lookupKey);
    }

    if (found.isEmpty()) {
      return Optional.empty();
    }

    IdempotencyKey key = found.get();

    if (key.isExpiredAt(now)) {
      log.info(
          "Idempotency key expired: lookupKey={}, deterministicKey={}, expiresAt={}",
          maskKey(lookupKey),
          maskKey(deterministicKey),
          key.getExpiresAt());
      return Optional.of(IdempotencyResult.expired(deterministicKey));
    }

    if (key.getStatus() == IdempotencyStatus.COMPLETED) {
      log.info(
          "Idempotency key hit: lookupKey={}, deterministicKey={}, eventId={}",
          maskKey(lookupKey),
          maskKey(deterministicKey),
          key.getEventId());
      return Optional.of(IdempotencyResult.hit(deterministicKey, key.getEventId()));
    }

    log.info(
        "Idempotency key still processing: lookupKey={}, deterministicKey={}",
        maskKey(lookupKey),
        maskKey(deterministicKey));
    return Optional.of(IdempotencyResult.processing(deterministicKey));
  }

  private IdempotencyResult insertNewKey(
      String clientProvidedKey, String deterministicKey, Instant now) {
    UUID eventId = UUID.randomUUID();
    Duration ttl = calculateTtl(clientProvidedKey);
    Instant expiresAt = now.plus(ttl);

    int inserted =
        repository.insertIfNotExists(
            deterministicKey,
            clientProvidedKey,
            eventId,
            IdempotencyStatus.PROCESSING.name(),
            now,
            expiresAt);

    if (inserted > 0) {
      log.info(
          "Idempotency key miss (new): deterministicKey={}, clientKey={}, eventId={}, ttl={}",
          maskKey(deterministicKey),
          maskKey(clientProvidedKey),
          eventId,
          ttl.toHours() + "h");
      return IdempotencyResult.miss(deterministicKey, eventId);
    }

    return handleConcurrentInsert(deterministicKey);
  }

  private IdempotencyResult handleConcurrentInsert(String deterministicKey) {
    IdempotencyKey concurrentKey =
        repository
            .findByKeyHash(deterministicKey)
            .orElseThrow(() -> new IllegalStateException("Key should exist after failed insert"));

    if (concurrentKey.getStatus() == IdempotencyStatus.COMPLETED) {
      log.info(
          "Idempotency key hit (concurrent): deterministicKey={}, eventId={}",
          maskKey(deterministicKey),
          concurrentKey.getEventId());
      return IdempotencyResult.hit(deterministicKey, concurrentKey.getEventId());
    }

    log.info(
        "Idempotency key still processing (concurrent): deterministicKey={}",
        maskKey(deterministicKey));
    return IdempotencyResult.processing(deterministicKey);
  }

  private Duration calculateTtl(String clientProvidedKey) {
    if (hasValue(clientProvidedKey)) {
      return Duration.ofHours(clientProvidedTtlHours);
    }
    return Duration.ofHours(autoGeneratedTtlHours);
  }

  private String resolveDeterministicKey(String nationalId, String sourceSystem) {
    return IdempotencyKeyGenerator.generate(nationalId, sourceSystem);
  }

  private static boolean hasValue(String value) {
    return value != null && !value.isBlank();
  }

  private static String maskKey(String key) {
    if (key == null || key.length() <= 8) {
      return "***";
    }
    return key.substring(0, 4) + "..." + key.substring(key.length() - 4);
  }

  // ─── Sealed result types ───────────────────────────────────────────────────

  public sealed interface IdempotencyResult {
    String keyHash();

    UUID eventId();

    static IdempotencyResult hit(String keyHash, UUID eventId) {
      return new IdempotencyHit(keyHash, eventId);
    }

    static IdempotencyResult miss(String keyHash, UUID eventId) {
      return new IdempotencyMiss(keyHash, eventId);
    }

    static IdempotencyResult processing(String keyHash) {
      return new IdempotencyProcessing(keyHash);
    }

    static IdempotencyResult expired(String keyHash) {
      return new IdempotencyExpired(keyHash);
    }
  }

  public record IdempotencyHit(String keyHash, UUID eventId) implements IdempotencyResult {}

  public record IdempotencyMiss(String keyHash, UUID eventId) implements IdempotencyResult {}

  public record IdempotencyProcessing(String keyHash) implements IdempotencyResult {
    @Override
    public UUID eventId() {
      return null;
    }
  }

  public record IdempotencyExpired(String keyHash) implements IdempotencyResult {
    @Override
    public UUID eventId() {
      return null;
    }
  }
}
